<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale-1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Главная страница</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.cdnfonts.com/css/days-2" rel="stylesheet">
    <link href="https://fonts.cdnfonts.com/css/videopac" rel="stylesheet">
    <link rel="icon" type="image/png" href="/src/image/icon.png">
    <link href='https://fonts.googleapis.com/css?family=Passion+One|Cantarell:400,400italic,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/youplay/css/youplay-anime.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/magnific-popup/dist/magnific-popup.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/social-likes/dist/social-likes_flat.css" />
    <link rel="stylesheet" type="text/css" href="/src/css/common/common.css" />
    <link rel="stylesheet" type="text/css" href="/src/css/neon/neon-text.css">
    <link rel="stylesheet" type="text/css" href="/src/css/pushbutton/pushbutton.css">
    <link rel="stylesheet" type="text/css" href="/src/css/background/background.css">
</head>
<body>
    <nav class="navbar-youplay navbar navbar-default navbar-fixed-top navbar-small">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    <img src="../../src/image/logo.png" alt="">
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <button
                                class="pushbutton__glow-on-hover"
                                onclick="window.location.href = '/'"
                        >
                            Главная страница
                        </button>
                    </li>
                    <li>
                        <button
                                class="pushbutton__glow-on-hover"
                                onclick="window.location.href = '/player'"
                        >
                            Личный кабинет
                        </button>
                    </li>
                    <li>
                        <button
                                class="pushbutton__glow-on-hover"
                                onclick="window.location.href = '/library'"
                        >
                            Библиотека
                        </button>
                    </li>
                    <li>
                        <button
                                class="pushbutton__glow-on-hover"
                                onclick="window.location.href = '/game'"
                        >
                            Игры
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <section class="content-wrap">
        <section class="youplay-banner banner-top big youplay-banner-parallax background_anime">
            <div class="info">
                <div>
                    <div class="container">
                        <div class="main-text neon-text">
                            Orion
                            Games
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <footer class="youplay-footer-parallax">
            <div
                    class="wrapper"
                    style="background-image: url('/src/image/footer-bg.jpg')"
            >
                <div class="social">
                    <div class="container">
                        <h3>Социальные сети <strong>Orion Games</strong></h3>

                        <div class="social-icons">
                            <div class="social-icon">
                                <a
                                        href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley"
                                        target="_blank"
                                >
                                    <img
                                            class="fa fa-youtube"
                                            src="https://cdn141.picsart.com/327737999037201.jpg"
                                            width="72px"
                                            height="72px"
                                            alt="">
                                    <span>Смотрите на ютубе</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="copyright">
                    <div class="container">
                        <strong>Orion Games</strong> &copy; 2023. Все права защищены
                    </div>
                </div>
            </div>
        </footer>
    </section>
</body>
</html>