<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale-1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Главная страница</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.cdnfonts.com/css/days-2" rel="stylesheet">
    <link rel="icon" type="image/png" href="/src/image/icon.png">
    <link href='https://fonts.googleapis.com/css?family=Passion+One|Cantarell:400,400italic,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/youplay/css/youplay-anime.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/css/common/common.css" />
    <link rel="stylesheet" type="text/css" href="/src/css/neon/neon-text.css">
</head>
<body>
    <nav class="navbar-youplay navbar navbar-default navbar-fixed-top navbar-small">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    <img src="../../../maket/image/logo.png" alt="">
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/">Главная страница</a>
                    </li>
                    <li>
                        <a href="/player">Личный кабинет</a>
                    </li>
                    <li>
                        <a href="/library">Библиотека</a>
                    </li>
                    <li>
                        <a href="/game">Игры</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <section class="content-wrap main-size">
        <section class="youplay-banner banner-top big youplay-banner-parallax background_anime">
            <div class="info">
                <div>
                    <div class="container">
                        <div class="main-text neon-text">
                            Orion
                            <br>
                            Games
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</body>
</html>